<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;


class ItemSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $itemcategory = [
            ['name' => 'GRINDING COLOR KURSI', 'type' => 'RM', 'unit' => 'kg', 'weight' => null, 'rate' => 26, 'gst_rate' => 0, 'hsn_code' => 0, 'opening_stock' => 0, 'min_stock_qty' => 10000, 'maintain_stock' => 'yes', 'item_barcode' => null, 'discount' => 0, 'is_bom' => 'yes', 'item_group_id' => 1, 'item_category_id' => 1],
            ['name' => 'GRINDING WHITE KURSI', 'type' => 'RM', 'unit' => 'kg', 'weight' => null, 'rate' => 40, 'gst_rate' => 0, 'hsn_code' => '', 'opening_stock' => 0, 'min_stock_qty' => 10000, 'maintain_stock' => 'yes', 'item_barcode' => null, 'discount' => 0, 'is_bom' => 'yes', 'item_group_id' => 1, 'item_category_id' => 1],
            ['name' => 'GRINDING WHITE PP', 'type' => 'RM', 'unit' => 'kg', 'weight' => null, 'rate' => 42, 'gst_rate' => 0, 'hsn_code' => 0, 'opening_stock' => 0, 'min_stock_qty' => 2500, 'maintain_stock' => 'yes', 'item_barcode' => null, 'discount' => 0, 'is_bom' => 'yes', 'item_group_id' => 1, 'item_category_id' => 1],
            ['name' => 'GRINDING COLOR PP', 'type' => 'RM', 'unit' => 'kg', 'weight' => null, 'rate' => 34, 'gst_rate' => 0, 'hsn_code' => 0, 'opening_stock' => 0, 'min_stock_qty' => 2500, 'maintain_stock' => 'yes', 'item_barcode' => null, 'discount' => 0, 'is_bom' => 'yes', 'item_group_id' => 1, 'item_category_id' => 1],
            ['name' => 'GRINDING NATURAL PP KADAK', 'type' => 'RM', 'unit' => 'kg', 'weight' => null, 'rate' => 52, 'gst_rate' => 0, 'hsn_code' => 0, 'opening_stock' => 0, 'min_stock_qty' => 2500, 'maintain_stock' => 'yes', 'item_barcode' => null, 'discount' => 0, 'is_bom' => 'yes', 'item_group_id' => 1, 'item_category_id' => 1],
            ['name' => 'GRINDING NATURAL PP ICE GLASS', 'type' => 'RM', 'unit' => 'kg', 'weight' => null, 'rate' => 42, 'gst_rate' => 0, 'hsn_code' => 0, 'opening_stock' => 0, 'min_stock_qty' => 2500, 'maintain_stock' => 'yes', 'item_barcode' => null, 'discount' => 0, 'is_bom' => 'yes', 'item_group_id' => 1, 'item_category_id' => 1],
            ['name' => 'GRINDING WHITE PATTI', 'type' => 'RM', 'unit' => 'kg', 'weight' => null, 'rate' => 27, 'gst_rate' => 0, 'hsn_code' => 0, 'opening_stock' => 0, 'min_stock_qty' => 500, 'maintain_stock' => 'yes', 'item_barcode' => null, 'discount' => 0, 'is_bom' => 'yes', 'item_group_id' => 1, 'item_category_id' => 1],
            ['name' => 'DANA NATURAL 1 (VIRGIN)', 'type' => 'RM', 'unit' => 'kg', 'weight' => null, 'rate' => 77, 'gst_rate' => 0, 'hsn_code' => 0, 'opening_stock' => 0, 'min_stock_qty' => 1500, 'maintain_stock' => 'yes', 'item_barcode' => null, 'discount' => 0, 'is_bom' => 'yes', 'item_group_id' => 1, 'item_category_id' => 1],
            ['name' => 'DANA NATURAL 2 ( DULL)', 'type' => 'RM', 'unit' => 'kg', 'weight' => null, 'rate' => 72, 'gst_rate' => 0, 'hsn_code' => 0, 'opening_stock' => 0, 'min_stock_qty' => 1500, 'maintain_stock' => 'yes', 'item_barcode' => null, 'discount' => 0, 'is_bom' => 'yes', 'item_group_id' => 1, 'item_category_id' => 1],
            ['name' => 'DANA NATURAL 3 (FOR BROWN)', 'type' => 'RM', 'unit' => 'kg', 'weight' => null, 'rate' => 60, 'gst_rate' => 0, 'hsn_code' => 0, 'opening_stock' => 0, 'min_stock_qty' => 2500, 'maintain_stock' => 'yes', 'item_barcode' => null, 'discount' => 0, 'is_bom' => 'yes', 'item_group_id' => 1, 'item_category_id' => 1],
            ['name' => 'DANA JUMBO WHITE ', 'type' => 'RM', 'unit' => 'kg', 'weight' => null, 'rate' => 60, 'gst_rate' => 0, 'hsn_code' => 0, 'opening_stock' => 0, 'min_stock_qty' => 2000, 'maintain_stock' => 'yes', 'item_barcode' => null, 'discount' => 0, 'is_bom' => 'yes', 'item_group_id' => 1, 'item_category_id' => 1],
            ['name' => 'DANA VIRGIN PP HP', 'type' => 'RM', 'unit' => 'kg', 'weight' => null, 'rate' => 95, 'gst_rate' => 0, 'hsn_code' => 0, 'opening_stock' => 0, 'min_stock_qty' => 2000, 'maintain_stock' => 'yes', 'item_barcode' => null, 'discount' => 0, 'is_bom' => 'yes', 'item_group_id' => 1, 'item_category_id' => 1],
            ['name' => 'DANA VIRGIN PP CP', 'type' => 'RM', 'unit' => 'kg', 'weight' => null, 'rate' => 105, 'gst_rate' => 0, 'hsn_code' => 0, 'opening_stock' => 0, 'min_stock_qty' => 2000, 'maintain_stock' => 'yes', 'item_barcode' => null, 'discount' => 0, 'is_bom' => 'yes', 'item_group_id' => 1, 'item_category_id' => 1],
            ['name' => 'DANA WHITE PVDC', 'type' => 'RM', 'unit' => 'kg', 'weight' => null, 'rate' => 90, 'gst_rate' => 0, 'hsn_code' => 0, 'opening_stock' => 0, 'min_stock_qty' => 2000, 'maintain_stock' => 'yes', 'item_barcode' => null, 'discount' => 0, 'is_bom' => 'yes', 'item_group_id' => 1, 'item_category_id' => 1],
            ['name' => 'DANA WHITE MORMAT', 'type' => 'RM', 'unit' => 'kg', 'weight' => null, 'rate' => 80, 'gst_rate' => 0, 'hsn_code' => 0, 'opening_stock' => 0, 'min_stock_qty' => 2000, 'maintain_stock' => 'yes', 'item_barcode' => null, 'discount' => 0, 'is_bom' => 'yes', 'item_group_id' => 1, 'item_category_id' => 1],
            ['name' => 'DANA IMPORTED NATURAL', 'type' => 'RM', 'unit' => 'kg', 'weight' => null, 'rate' => 82, 'gst_rate' => 0, 'hsn_code' => 0, 'opening_stock' => 0, 'min_stock_qty' => 2000, 'maintain_stock' => 'yes', 'item_barcode' => null, 'discount' => 0, 'is_bom' => 'yes', 'item_group_id' => 1, 'item_category_id' => 1],
            ['name' => 'DANA RED DUKAN ', 'type' => 'RM', 'unit' => 'kg', 'weight' => null, 'rate' => 48, 'gst_rate' => 0, 'hsn_code' => 0, 'opening_stock' => 0, 'min_stock_qty' => 5000, 'maintain_stock' => 'yes', 'item_barcode' => null, 'discount' => 0, 'is_bom' => 'yes', 'item_group_id' => 1, 'item_category_id' => 1],
            ['name' => 'DANA ORANGE DUKAN', 'type' => 'RM', 'unit' => 'kg', 'weight' => null, 'rate' => 48, 'gst_rate' => 0, 'hsn_code' => 0, 'opening_stock' => 0, 'min_stock_qty' => 5000, 'maintain_stock' => 'yes', 'item_barcode' => null, 'discount' => 0, 'is_bom' => 'yes', 'item_group_id' => 1, 'item_category_id' => 1],
            ['name' => 'DANA BISCUIT DUKAN', 'type' => 'RM', 'unit' => 'kg', 'weight' => null, 'rate' => 48, 'gst_rate' => 0, 'hsn_code' => 0, 'opening_stock' => 0, 'min_stock_qty' => 5000, 'maintain_stock' => 'yes', 'item_barcode' => null, 'discount' => 0, 'is_bom' => 'yes', 'item_group_id' => 1, 'item_category_id' => 1],
            ['name' => 'DANA BROWN DUKAN', 'type' => 'RM', 'unit' => 'kg', 'weight' => null, 'rate' => 48, 'gst_rate' => 0, 'hsn_code' => 0, 'opening_stock' => 0, 'min_stock_qty' => 5000, 'maintain_stock' => 'yes', 'item_barcode' => null, 'discount' => 0, 'is_bom' => 'yes', 'item_group_id' => 1, 'item_category_id' => 1],
            ['name' => 'DANA FERI MARUN', 'type' => 'RM', 'unit' => 'kg', 'weight' => null, 'rate' => 33, 'gst_rate' => 0, 'hsn_code' => 0, 'opening_stock' => 0, 'min_stock_qty' => 3500, 'maintain_stock' => 'yes', 'item_barcode' => null, 'discount' => 0, 'is_bom' => 'yes', 'item_group_id' => 1, 'item_category_id' => 1],
            ['name' => 'DANA FERI VOILET', 'type' => 'RM', 'unit' => 'kg', 'weight' => null, 'rate' => 33, 'gst_rate' => 0, 'hsn_code' => 0, 'opening_stock' => 0, 'min_stock_qty' => 3500, 'maintain_stock' => 'yes', 'item_barcode' => null, 'discount' => 0, 'is_bom' => 'yes', 'item_group_id' => 1, 'item_category_id' => 1],
            ['name' => 'DANA FERI CHOCLATE', 'type' => 'RM', 'unit' => 'kg', 'weight' => null, 'rate' => 33, 'gst_rate' => 0, 'hsn_code' => 0, 'opening_stock' => 0, 'min_stock_qty' => 1500, 'maintain_stock' => 'yes', 'item_barcode' => null, 'discount' => 0, 'is_bom' => 'yes', 'item_group_id' => 1, 'item_category_id' => 1],
            ['name' => 'DANA FILLER', 'type' => 'RM', 'unit' => 'kg', 'weight' => null, 'rate' => 35, 'gst_rate' => 0, 'hsn_code' => 0, 'opening_stock' => 0, 'min_stock_qty' => 3000, 'maintain_stock' => 'yes', 'item_barcode' => null, 'discount' => 0, 'is_bom' => 'yes', 'item_group_id' => 1, 'item_category_id' => 1],
            ['name' => 'DANA KJ NATURAL ', 'type' => 'RM', 'unit' => 'kg', 'weight' => null, 'rate' => 58, 'gst_rate' => 0, 'hsn_code' => 0, 'opening_stock' => 0, 'min_stock_qty' => 1500, 'maintain_stock' => 'yes', 'item_barcode' => null, 'discount' => 0, 'is_bom' => 'yes', 'item_group_id' => 1, 'item_category_id' => 1],
            ['name' => 'DANA FERI RED', 'type' => 'RM', 'unit' => 'kg', 'weight' => null, 'rate' => 48, 'gst_rate' => 0, 'hsn_code' => '', 'opening_stock' => 0, 'min_stock_qty' => 2000, 'maintain_stock' => 'yes', 'item_barcode' => null, 'discount' => 0, 'is_bom' => 'yes', 'item_group_id' => 1, 'item_category_id' => 1],
            ['name' => 'DANA FERI ORANGE', 'type' => 'RM', 'unit' => 'kg', 'weight' => null, 'rate' => 48, 'gst_rate' => 0, 'hsn_code' => 0, 'opening_stock' => 0, 'min_stock_qty' => 2000, 'maintain_stock' => 'yes', 'item_barcode' => null, 'discount' => 0, 'is_bom' => 'yes', 'item_group_id' => 1, 'item_category_id' => 1],
            ['name' => 'DANA FERI PINK', 'type' => 'RM', 'unit' => 'kg', 'weight' => null, 'rate' => 48, 'gst_rate' => 0, 'hsn_code' => 0, 'opening_stock' => 0, 'min_stock_qty' => 500, 'maintain_stock' => 'yes', 'item_barcode' => null, 'discount' => 0, 'is_bom' => 'yes', 'item_group_id' => 1, 'item_category_id' => 1],
            ['name' => 'DANA FERI BISCUIT', 'type' => 'RM', 'unit' => 'kg', 'weight' => null, 'rate' => 48, 'gst_rate' => 0, 'hsn_code' => 0, 'opening_stock' => 0, 'min_stock_qty' => 2000, 'maintain_stock' => 'yes', 'item_barcode' => null, 'discount' => 0, 'is_bom' => 'yes', 'item_group_id' => 1, 'item_category_id' => 1],
            ['name' => 'DELTA MOISTURE', 'type' => 'RM', 'unit' => 'kg', 'weight' => null, 'rate' => 14, 'gst_rate' => 0, 'hsn_code' => 0, 'opening_stock' => 0, 'min_stock_qty' => 4000, 'maintain_stock' => 'yes', 'item_barcode' => null, 'discount' => 0, 'is_bom' => 'yes', 'item_group_id' => 1, 'item_category_id' => 1],
            ['name' => 'DANA IMPORTED NATURAL SWEPPING', 'type' => 'RM', 'unit' => 'kg', 'weight' => null, 'rate' => 70, 'gst_rate' => 0, 'hsn_code' => 0, 'opening_stock' => 0, 'min_stock_qty' => 1500, 'maintain_stock' => 'yes', 'item_barcode' => null, 'discount' => 0, 'is_bom' => 'yes', 'item_group_id' => 1, 'item_category_id' => 1],
            ['name' => 'MB-BLEND  T RED', 'type' => 'RM', 'unit' => 'kg', 'weight' => null, 'rate' => 200, 'gst_rate' => 0, 'hsn_code' => 0, 'opening_stock' => 0, 'min_stock_qty' => 200, 'maintain_stock' => 'yes', 'item_barcode' => null, 'discount' => 0, 'is_bom' => 'yes', 'item_group_id' => 1, 'item_category_id' => 1],
            ['name' => 'MB-BLEND B RED ', 'type' => 'RM', 'unit' => 'kg', 'weight' => null, 'rate' => 200, 'gst_rate' => 0, 'hsn_code' => 0, 'opening_stock' => 0, 'min_stock_qty' => 300, 'maintain_stock' => 'yes', 'item_barcode' => null, 'discount' => 0, 'is_bom' => 'yes', 'item_group_id' => 1, 'item_category_id' => 1],
            ['name' => 'MB-BLEND D ORANGE', 'type' => 'RM', 'unit' => 'Nos', 'weight' => null, 'rate' => 150, 'gst_rate' => 0, 'hsn_code' => 0, 'opening_stock' => 0, 'min_stock_qty' => 200, 'maintain_stock' => 'yes', 'item_barcode' => null, 'discount' => 0, 'is_bom' => 'yes', 'item_group_id' => 1, 'item_category_id' => 1],
            ['name' => 'MB-BLEND C BROWN', 'type' => 'RM', 'unit' => 'kg', 'weight' => null, 'rate' => 150, 'gst_rate' => 0, 'hsn_code' => 0, 'opening_stock' => 0, 'min_stock_qty' => 400, 'maintain_stock' => 'yes', 'item_barcode' => null, 'discount' => 0, 'is_bom' => 'yes', 'item_group_id' => 1, 'item_category_id' => 1],
            ['name' => 'MB-BLEND EAGLE BROWN', 'type' => 'RM', 'unit' => 'kg', 'weight' => null, 'rate' => 170, 'gst_rate' => 0, 'hsn_code' => 0, 'opening_stock' => 0, 'min_stock_qty' => 100, 'maintain_stock' => 'yes', 'item_barcode' => null, 'discount' => 0, 'is_bom' => 'yes', 'item_group_id' => 1, 'item_category_id' => 1],
            ['name' => 'MB-BLEND MARBLE BEAGE', 'type' => 'RM', 'unit' => 'kg', 'weight' => null, 'rate' => 180, 'gst_rate' => 0, 'hsn_code' => 0, 'opening_stock' => 0, 'min_stock_qty' => 50, 'maintain_stock' => 'yes', 'item_barcode' => null, 'discount' => 0, 'is_bom' => 'yes', 'item_group_id' => 1, 'item_category_id' => 1],
            ['name' => 'MB-BLEND SANDLE YELLOW', 'type' => 'RM', 'unit' => 'kg', 'weight' => null, 'rate' => 150, 'gst_rate' => 0, 'hsn_code' => 0, 'opening_stock' => 0, 'min_stock_qty' => 150, 'maintain_stock' => 'yes', 'item_barcode' => null, 'discount' => 0, 'is_bom' => 'yes', 'item_group_id' => 1, 'item_category_id' => 1],
            ['name' => 'MB-BLEND ECO DELUX WHITE', 'type' => 'RM', 'unit' => 'kg', 'weight' => null, 'rate' => 150, 'gst_rate' => 0, 'hsn_code' => 0, 'opening_stock' => 0, 'min_stock_qty' => 50, 'maintain_stock' => 'yes', 'item_barcode' => null, 'discount' => 0, 'is_bom' => 'yes', 'item_group_id' => 1, 'item_category_id' => 1],
            ['name' => 'MB-BLEND METALLIC SILVER', 'type' => 'RM', 'unit' => 'kg', 'weight' => null, 'rate' => 220, 'gst_rate' => 0, 'hsn_code' => 0, 'opening_stock' => 0, 'min_stock_qty' => 25, 'maintain_stock' => 'yes', 'item_barcode' => null, 'discount' => 0, 'is_bom' => 'yes', 'item_group_id' => 1, 'item_category_id' => 1],
            ['name' => 'MB-BLEND WHITE MARBLE', 'type' => 'RM', 'unit' => 'kg', 'weight' => null, 'rate' => 170, 'gst_rate' => 0, 'hsn_code' => 0, 'opening_stock' => 0, 'min_stock_qty' => 25, 'maintain_stock' => 'yes', 'item_barcode' => null, 'discount' => 0, 'is_bom' => 'yes', 'item_group_id' => 1, 'item_category_id' => 1],
            ['name' => 'MB-LOCAL WHITE', 'type' => 'RM', 'unit' => 'kg', 'weight' => null, 'rate' => 220, 'gst_rate' => 0, 'hsn_code' => 0, 'opening_stock' => 0, 'min_stock_qty' => 150, 'maintain_stock' => 'yes', 'item_barcode' => null, 'discount' => 0, 'is_bom' => 'yes', 'item_group_id' => 1, 'item_category_id' => 1],
            ['name' => 'MB-NTR BLOOD RED', 'type' => 'RM', 'unit' => 'kg', 'weight' => null, 'rate' => 175, 'gst_rate' => 0, 'hsn_code' => 0, 'opening_stock' => 0, 'min_stock_qty' => 25, 'maintain_stock' => 'yes', 'item_barcode' => null, 'discount' => 0, 'is_bom' => 'yes', 'item_group_id' => 1, 'item_category_id' => 1],
            ['name' => 'MB-NTR BLUE', 'type' => 'RM', 'unit' => 'kg', 'weight' => null, 'rate' => 175, 'gst_rate' => 0, 'hsn_code' => 0, 'opening_stock' => 0, 'min_stock_qty' => 50, 'maintain_stock' => 'yes', 'item_barcode' => null, 'discount' => 0, 'is_bom' => 'yes', 'item_group_id' => 1, 'item_category_id' => 1],
            ['name' => 'MB-NTR PINK', 'type' => 'RM', 'unit' => 'kg', 'weight' => null, 'rate' => 200, 'gst_rate' => 0, 'hsn_code' => 0, 'opening_stock' => 0, 'min_stock_qty' => 25, 'maintain_stock' => 'yes', 'item_barcode' => null, 'discount' => 0, 'is_bom' => 'yes', 'item_group_id' => 1, 'item_category_id' => 1],
            ['name' => 'MB-NTR BLACK', 'type' => 'RM', 'unit' => 'kg', 'weight' => null, 'rate' => 140, 'gst_rate' => 0, 'hsn_code' => 0, 'opening_stock' => 0, 'min_stock_qty' => 25, 'maintain_stock' => 'yes', 'item_barcode' => null, 'discount' => 0, 'is_bom' => 'yes', 'item_group_id' => 1, 'item_category_id' => 1],
            ['name' => 'MB-NTR GREEN PISTA ', 'type' => 'RM', 'unit' => 'kg', 'weight' => null, 'rate' => 175, 'gst_rate' => 0, 'hsn_code' => 0, 'opening_stock' => 0, 'min_stock_qty' => 50, 'maintain_stock' => 'yes', 'item_barcode' => null, 'discount' => 0, 'is_bom' => 'yes', 'item_group_id' => 1, 'item_category_id' => 1],
            ['name' => 'MB-NTR VIRGIN BEAGE', 'type' => 'RM', 'unit' => 'kg', 'weight' => null, 'rate' => 175, 'gst_rate' => 0, 'hsn_code' => 0, 'opening_stock' => 0, 'min_stock_qty' => 200, 'maintain_stock' => 'yes', 'item_barcode' => null, 'discount' => 0, 'is_bom' => 'yes', 'item_group_id' => 1, 'item_category_id' => 1],
            ['name' => 'MB-NTR SEMI BEAGE ', 'type' => 'RM', 'unit' => 'kg', 'weight' => null, 'rate' => 175, 'gst_rate' => 0, 'hsn_code' => 0, 'opening_stock' => 0, 'min_stock_qty' => 300, 'maintain_stock' => 'yes', 'item_barcode' => null, 'discount' => 0, 'is_bom' => 'yes', 'item_group_id' => 1, 'item_category_id' => 1],
            ['name' => 'MB-NTR METALLIC BROWN', 'type' => 'RM', 'unit' => 'kg', 'weight' => null, 'rate' => 220, 'gst_rate' => 0, 'hsn_code' => '', 'opening_stock' => 0, 'min_stock_qty' => 25, 'maintain_stock' => 'yes', 'item_barcode' => null, 'discount' => 0, 'is_bom' => 'yes', 'item_group_id' => 1, 'item_category_id' => 1],
            ['name' => 'MB-SUDARSHAN YELLOW', 'type' => 'RM', 'unit' => 'kg', 'weight' => null, 'rate' => 200, 'gst_rate' => 0, 'hsn_code' => 0, 'opening_stock' => 0, 'min_stock_qty' => 100, 'maintain_stock' => 'yes', 'item_barcode' => null, 'discount' => 0, 'is_bom' => 'yes', 'item_group_id' => 1, 'item_category_id' => 1],
            ['name' => 'WRAPPING ROOLS ', 'type' => 'RM', 'unit' => 'kg', 'weight' => null, 'rate' => 135, 'gst_rate' => 0, 'hsn_code' => 0, 'opening_stock' => 0, 'min_stock_qty' => 250, 'maintain_stock' => 'yes', 'item_barcode' => null, 'discount' => 0, 'is_bom' => 'yes', 'item_group_id' => 1, 'item_category_id' => 1],
            ['name' => 'SQ DINING POLLY 35*50*100', 'type' => 'RM', 'unit' => 'kg', 'weight' => null, 'rate' => 132, 'gst_rate' => 0, 'hsn_code' => 0, 'opening_stock' => 0, 'min_stock_qty' => 25, 'maintain_stock' => 'yes', 'item_barcode' => null, 'discount' => 0, 'is_bom' => 'yes', 'item_group_id' => 1, 'item_category_id' => 1],
            ['name' => 'RD DINING POLLY ', 'type' => 'RM', 'unit' => 'kg', 'weight' => null, 'rate' => 135, 'gst_rate' => 0, 'hsn_code' => 0, 'opening_stock' => 0, 'min_stock_qty' => 25, 'maintain_stock' => 'yes', 'item_barcode' => null, 'discount' => 0, 'is_bom' => 'yes', 'item_group_id' => 1, 'item_category_id' => 1],
            ['name' => 'CARTON SQ TOP SL', 'type' => 'RM', 'unit' => 'Nos', 'weight' => null, 'rate' => 50, 'gst_rate' => 0, 'hsn_code' => 0, 'opening_stock' => 0, 'min_stock_qty' => 100, 'maintain_stock' => 'yes', 'item_barcode' => null, 'discount' => 0, 'is_bom' => 'yes', 'item_group_id' => 1, 'item_category_id' => 1],
            ['name' => 'CARTON SQ TOP CL', 'type' => 'RM', 'unit' => 'Nos', 'weight' => null, 'rate' => 50, 'gst_rate' => 0, 'hsn_code' => 0, 'opening_stock' => 0, 'min_stock_qty' => 100, 'maintain_stock' => 'yes', 'item_barcode' => null, 'discount' => 0, 'is_bom' => 'yes', 'item_group_id' => 1, 'item_category_id' => 1],
            ['name' => 'CARTON ROUND TOP SL', 'type' => 'RM', 'unit' => 'Nos', 'weight' => null, 'rate' => 50, 'gst_rate' => 0, 'hsn_code' => 0, 'opening_stock' => 0, 'min_stock_qty' => 50, 'maintain_stock' => 'yes', 'item_barcode' => null, 'discount' => 0, 'is_bom' => 'yes', 'item_group_id' => 1, 'item_category_id' => 1],
            ['name' => 'CARTON ROUND TOP CL', 'type' => 'RM', 'unit' => 'Nos', 'weight' => null, 'rate' => 50, 'gst_rate' => 0, 'hsn_code' => 0, 'opening_stock' => 0, 'min_stock_qty' => 100, 'maintain_stock' => 'yes', 'item_barcode' => null, 'discount' => 0, 'is_bom' => 'yes', 'item_group_id' => 1, 'item_category_id' => 1],
            ['name' => 'BUBBLE ROLLS', 'type' => 'RM', 'unit' => 'kg', 'weight' => null, 'rate' => 135, 'gst_rate' => 0, 'hsn_code' => 0, 'opening_stock' => 0, 'min_stock_qty' => 100, 'maintain_stock' => 'yes', 'item_barcode' => null, 'discount' => 0, 'is_bom' => 'yes', 'item_group_id' => 1, 'item_category_id' => 1],
            ['name' => 'handle', 'type' => 'RM', 'unit' => 'Nos', 'weight' => null, 'rate' => 10, 'gst_rate' => 0, 'hsn_code' => 1000, 'opening_stock' => 1000, 'min_stock_qty' => 10, 'maintain_stock' => 'yes', 'item_barcode' => null, 'discount' => 0, 'is_bom' => 'yes', 'item_group_id' => 1, 'item_category_id' => 1],
        ];
        DB::table('items')->insert($itemcategory);
    }
}
