<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PaymentReceiptSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $paymentReceipt = [
            ['ledger_id' => 69, 'amount' => 17000, 'date' => '2024-05-13', 'mode' => 'Cash', 'vch_type' => 'receipt', 'vch_no' => 1, 'from' => 6, 'details' => 'CASH TO SANJU', 'created_by' => 1, 'updated_by' => 1],
            ['ledger_id' => 70, 'amount' => 8610, 'date' => '2024-05-13', 'mode' => 'Cash', 'vch_type' => 'receipt', 'vch_no' => 2, 'from' => 6, 'details' => 'CASH TO SANJU', 'created_by' => 1, 'updated_by' => 1],
            ['ledger_id' => 55, 'amount' => 15000, 'date' => '2024-05-13', 'mode' => 'Cash', 'vch_type' => 'receipt', 'vch_no' => 3, 'from' => 6, 'details' => 'CASH TO SANJU', 'created_by' => 1, 'updated_by' => 1],
            ['ledger_id' => 75, 'amount' => 12740, 'date' => '2024-05-13', 'mode' => 'Cash', 'vch_type' => 'receipt', 'vch_no' => 4, 'from' => 6, 'details' => 'CASH TO SANJU', 'created_by' => 1, 'updated_by' => 1],
            ['ledger_id' => 62, 'amount' => 10000, 'date' => '2024-05-13', 'mode' => 'Cash', 'vch_type' => 'receipt', 'vch_no' => 5, 'from' => 6, 'details' => 'CASH TO SANJU', 'created_by' => 1, 'updated_by' => 1],
            ['ledger_id' => 591, 'amount' => 5850, 'date' => '2024-05-14', 'mode' => 'Cash', 'vch_type' => 'receipt', 'vch_no' => 6, 'from' => 6, 'details' => 'TEMP FOR NANDURBAR SONGAD MARKETING', 'created_by' => 1, 'updated_by' => 1],
            ['ledger_id' => 592, 'amount' => 70500, 'date' => '2024-05-14', 'mode' => '', 'vch_type' => 'receipt', 'vch_no' => 7, 'from' => 6, 'details' => 'RETAIL SALE S-327', 'created_by' => 1, 'updated_by' => 1],
            ['ledger_id' => 321, 'amount' => 280000, 'date' => '2024-05-12', 'mode' => 'Cash', 'vch_type' => 'receipt', 'vch_no' => 8, 'from' => 6, 'details' => 'TO VINOD AKOLA', 'created_by' => 1, 'updated_by' => 1],
            ['ledger_id' => 599, 'amount' => 950, 'date' => '2024-05-12', 'mode' => 'Cash', 'vch_type' => 'receipt', 'vch_no' => 9, 'from' => 6, 'details' => 'VARAI SULTAN SOLAPUR P-103', 'created_by' => 1, 'updated_by' => 1],
            ['ledger_id' => 598, 'amount' => 1000, 'date' => '2024-05-12', 'mode' => 'Cash', 'vch_type' => 'receipt', 'vch_no' => 10, 'from' => 6, 'details' => 'JAMA IN ADVANCE', 'created_by' => 1, 'updated_by' => 1],
            ['ledger_id' => 596, 'amount' => 3800, 'date' => '2024-05-12', 'mode' => 'Cash', 'vch_type' => 'receipt', 'vch_no' => 11, 'from' => 6, 'details' => '', 'created_by' => 1, 'updated_by' => 1],
            ['ledger_id' => 596, 'amount' => 100, 'date' => '2024-05-12', 'mode' => 'Cash', 'vch_type' => 'receipt', 'vch_no' => 12, 'from' => 6, 'details' => '', 'created_by' => 1, 'updated_by' => 1],
            ['ledger_id' => 604, 'amount' => 86500, 'date' => '2024-04-01', 'mode' => 'Cash', 'vch_type' => 'receipt', 'vch_no' => 13, 'from' => 6, 'details' => 'CASH', 'created_by' => 1, 'updated_by' => 1],
            ['ledger_id' => 605, 'amount' => 2500, 'date' => '2024-04-01', 'mode' => 'Cash', 'vch_type' => 'receipt', 'vch_no' => 14, 'from' => 6, 'details' => 'CASH', 'created_by' => 1, 'updated_by' => 1],
            ['ledger_id' => 259, 'amount' => 9900, 'date' => '2024-04-01', 'mode' => 'Cash', 'vch_type' => 'receipt', 'vch_no' => 15, 'from' => 6, 'details' => 'CASH', 'created_by' => 1, 'updated_by' => 1],
            ['ledger_id' => 231, 'amount' => 29800, 'date' => '2024-04-01', 'mode' => '', 'vch_type' => 'receipt', 'vch_no' => 16, 'from' => 6, 'details' => '', 'created_by' => 1, 'updated_by' => 1],
            ['ledger_id' => 128, 'amount' => 3000, 'date' => '2024-04-01', 'mode' => '', 'vch_type' => 'receipt', 'vch_no' => 17, 'from' => 6, 'details' => '', 'created_by' => 1, 'updated_by' => 1],
            ['ledger_id' => 123, 'amount' => 850, 'date' => '2024-04-01', 'mode' => 'Cash', 'vch_type' => 'receipt', 'vch_no' => 18, 'from' => 6, 'details' => '', 'created_by' => 1, 'updated_by' => 1],
            ['ledger_id' => 131, 'amount' => 10000, 'date' => '2024-04-01', 'mode' => 'Cash', 'vch_type' => 'receipt', 'vch_no' => 19, 'from' => 6, 'details' => '', 'created_by' => 1, 'updated_by' => 1],
            ['ledger_id' => 130, 'amount' => 22680, 'date' => '2024-04-01', 'mode' => 'Cash', 'vch_type' => 'receipt', 'vch_no' => 20, 'from' => 6, 'details' => '', 'created_by' => 1, 'updated_by' => 1],
            ['ledger_id' => 136, 'amount' => 5250, 'date' => '2024-04-01', 'mode' => 'Cash', 'vch_type' => 'receipt', 'vch_no' => 21, 'from' => 6, 'details' => '', 'created_by' => 1, 'updated_by' => 1],
            ['ledger_id' => 135, 'amount' => 20000, 'date' => '2024-04-01', 'mode' => 'Cash', 'vch_type' => 'receipt', 'vch_no' => 22, 'from' => 6, 'details' => '', 'created_by' => 1, 'updated_by' => 1],
            ['ledger_id' => 137, 'amount' => 40000, 'date' => '2024-04-01', 'mode' => 'Cash', 'vch_type' => 'receipt', 'vch_no' => 23, 'from' => 6, 'details' => '', 'created_by' => 1, 'updated_by' => 1],
            ['ledger_id' => 147, 'amount' => 5930, 'date' => '2024-04-01', 'mode' => 'Cash', 'vch_type' => 'receipt', 'vch_no' => 24, 'from' => 6, 'details' => '', 'created_by' => 1, 'updated_by' => 1],
            ['ledger_id' => 144, 'amount' => 10000, 'date' => '2024-04-01', 'mode' => 'Cash', 'vch_type' => 'receipt', 'vch_no' => 25, 'from' => 6, 'details' => '', 'created_by' => 1, 'updated_by' => 1],
            ['ledger_id' => 142, 'amount' => 12290, 'date' => '2024-04-01', 'mode' => 'Cash', 'vch_type' => 'receipt', 'vch_no' => 26, 'from' => 6, 'details' => '', 'created_by' => 1, 'updated_by' => 1],
            ['ledger_id' => 139, 'amount' => 31400, 'date' => '2024-04-01', 'mode' => 'Cash', 'vch_type' => 'receipt', 'vch_no' => 27, 'from' => 6, 'details' => '', 'created_by' => 1, 'updated_by' => 1],
            ['ledger_id' => 138, 'amount' => 36500, 'date' => '2024-04-01', 'mode' => 'Cash', 'vch_type' => 'receipt', 'vch_no' => 28, 'from' => 6, 'details' => '', 'created_by' => 1, 'updated_by' => 1],
            ['ledger_id' => 96, 'amount' => 5000, 'date' => '2024-04-01', 'mode' => 'Cash', 'vch_type' => 'receipt', 'vch_no' => 29, 'from' => 6, 'details' => '', 'created_by' => 1, 'updated_by' => 1],
            ['ledger_id' => 141, 'amount' => 30000, 'date' => '2024-04-01', 'mode' => 'Cash', 'vch_type' => 'receipt', 'vch_no' => 30, 'from' => 6, 'details' => '', 'created_by' => 1, 'updated_by' => 1],
            ['ledger_id' => 115, 'amount' => 18700, 'date' => '2024-04-01', 'mode' => 'Cash', 'vch_type' => 'receipt', 'vch_no' => 31, 'from' => 6, 'details' => '', 'created_by' => 1, 'updated_by' => 1],
            ['ledger_id' => 591, 'amount' => 6000, 'date' => '2024-04-01', 'mode' => 'Cash', 'vch_type' => 'receipt', 'vch_no' => 32, 'from' => 6, 'details' => '', 'created_by' => 1, 'updated_by' => 1],
            ['ledger_id' => 606, 'amount' => 25000, 'date' => '2024-04-01', 'mode' => 'Cash', 'vch_type' => 'receipt', 'vch_no' => 33, 'from' => 6, 'details' => '', 'created_by' => 1, 'updated_by' => 1],
            ['ledger_id' => 316, 'amount' => 15000, 'date' => '2024-04-01', 'mode' => 'Cash', 'vch_type' => 'receipt', 'vch_no' => 34, 'from' => 6, 'details' => '', 'created_by' => 1, 'updated_by' => 1],
            ['ledger_id' => 607, 'amount' => 1000, 'date' => '2024-04-01', 'mode' => 'Cash', 'vch_type' => 'receipt', 'vch_no' => 35, 'from' => 6, 'details' => '', 'created_by' => 1, 'updated_by' => 1],
            ['ledger_id' => 608, 'amount' => 3000, 'date' => '2024-04-01', 'mode' => 'Cash', 'vch_type' => 'receipt', 'vch_no' => 36, 'from' => 6, 'details' => 'JAMA', 'created_by' => 1, 'updated_by' => 1],
            ['ledger_id' => 226, 'amount' => 5000, 'date' => '2024-04-01', 'mode' => '', 'vch_type' => 'receipt', 'vch_no' => 37, 'from' => 6, 'details' => '', 'created_by' => 1, 'updated_by' => 1],
            ['ledger_id' => 265, 'amount' => 10000, 'date' => '2024-04-01', 'mode' => '', 'vch_type' => 'receipt', 'vch_no' => 38, 'from' => 6, 'details' => '', 'created_by' => 1, 'updated_by' => 1],
            ['ledger_id' => 252, 'amount' => 2800, 'date' => '2024-04-01', 'mode' => '', 'vch_type' => 'receipt', 'vch_no' => 39, 'from' => 6, 'details' => '', 'created_by' => 1, 'updated_by' => 1],
            ['ledger_id' => 249, 'amount' => 5000, 'date' => '2024-04-01', 'mode' => '', 'vch_type' => 'receipt', 'vch_no' => 40, 'from' => 6, 'details' => '', 'created_by' => 1, 'updated_by' => 1],
            ['ledger_id' => 248, 'amount' => 15000, 'date' => '2024-04-01', 'mode' => '', 'vch_type' => 'receipt', 'vch_no' => 41, 'from' => 6, 'details' => '', 'created_by' => 1, 'updated_by' => 1],
            ['ledger_id' => 215, 'amount' => 3960, 'date' => '2024-04-01', 'mode' => '', 'vch_type' => 'receipt', 'vch_no' => 42, 'from' => 6, 'details' => '', 'created_by' => 1, 'updated_by' => 1],
            ['ledger_id' => 336, 'amount' => 124000, 'date' => '2024-04-02', 'mode' => 'Cash', 'vch_type' => 'receipt', 'vch_no' => 43, 'from' => 6, 'details' => 'CASH', 'created_by' => 1, 'updated_by' => 1],
            ['ledger_id' => 615, 'amount' => 127800, 'date' => '2024-04-02', 'mode' => 'Cash', 'vch_type' => 'receipt', 'vch_no' => 44, 'from' => 6, 'details' => 'CASH', 'created_by' => 1, 'updated_by' => 1],
            ['ledger_id' => 616, 'amount' => 95800, 'date' => '2024-04-02', 'mode' => 'Cash', 'vch_type' => 'receipt', 'vch_no' => 45, 'from' => 6, 'details' => 'CASH', 'created_by' => 1, 'updated_by' => 1],
            ['ledger_id' => 618, 'amount' => 36800, 'date' => '2024-04-02', 'mode' => 'Cash', 'vch_type' => 'receipt', 'vch_no' => 46, 'from' => 6, 'details' => 'CASH', 'created_by' => 1, 'updated_by' => 1],
            ['ledger_id' => 617, 'amount' => 47100, 'date' => '2024-04-02', 'mode' => 'Cash', 'vch_type' => 'receipt', 'vch_no' => 47, 'from' => 6, 'details' => 'CASH', 'created_by' => 1, 'updated_by' => 1],
            ['ledger_id' => 620, 'amount' => 4000, 'date' => '2024-04-03', 'mode' => 'Cash', 'vch_type' => 'receipt', 'vch_no' => 48, 'from' => 6, 'details' => 'JAMA', 'created_by' => 1, 'updated_by' => 1],
            ['ledger_id' => 595, 'amount' => 2000, 'date' => '2024-04-03', 'mode' => 'Cash', 'vch_type' => 'receipt', 'vch_no' => 49, 'from' => 6, 'details' => 'LINE', 'created_by' => 1, 'updated_by' => 1],
            ['ledger_id' => 75, 'amount' => 10000, 'date' => '2024-04-03', 'mode' => 'Cash', 'vch_type' => 'receipt', 'vch_no' => 50, 'from' => 6, 'details' => '', 'created_by' => 1, 'updated_by' => 1],
            ['ledger_id' => 58, 'amount' => 17360, 'date' => '2024-04-03', 'mode' => 'Cash', 'vch_type' => 'receipt', 'vch_no' => 51, 'from' => 6, 'details' => '', 'created_by' => 1, 'updated_by' => 1],
            ['ledger_id' => 605, 'amount' => 4200, 'date' => '2024-04-03', 'mode' => 'Cash', 'vch_type' => 'receipt', 'vch_no' => 52, 'from' => 6, 'details' => '', 'created_by' => 1, 'updated_by' => 1],
            ['ledger_id' => 314, 'amount' => 120000, 'date' => '2024-04-03', 'mode' => 'Cash', 'vch_type' => 'receipt', 'vch_no' => 53, 'from' => 6, 'details' => '', 'created_by' => 1, 'updated_by' => 1],
            ['ledger_id' => 621, 'amount' => 17020, 'date' => '2024-04-03', 'mode' => 'Cash', 'vch_type' => 'receipt', 'vch_no' => 54, 'from' => 6, 'details' => 'TO ARSHAD MALEGAON', 'created_by' => 1, 'updated_by' => 1],
            ['ledger_id' => 596, 'amount' => 3265, 'date' => '2024-04-03', 'mode' => 'Cash', 'vch_type' => 'receipt', 'vch_no' => 55, 'from' => 6, 'details' => 'SWIFT DISEAL', 'created_by' => 1, 'updated_by' => 1],
            ['ledger_id' => 595, 'amount' => 2000, 'date' => '2024-04-03', 'mode' => 'Cash', 'vch_type' => 'receipt', 'vch_no' => 56, 'from' => 6, 'details' => 'LINE', 'created_by' => 1, 'updated_by' => 1],
            ['ledger_id' => 319, 'amount' => 200000, 'date' => '2024-04-04', 'mode' => 'Cash', 'vch_type' => 'receipt', 'vch_no' => 57, 'from' => 6, 'details' => '', 'created_by' => 1, 'updated_by' => 1],
            ['ledger_id' => 623, 'amount' => 9000, 'date' => '2024-04-04', 'mode' => 'Cash', 'vch_type' => 'receipt', 'vch_no' => 58, 'from' => 0, 'details' => 'jama', 'created_by' => 1, 'updated_by' => 1],
            ['ledger_id' => 624, 'amount' => 1500, 'date' => '2024-04-04', 'mode' => 'Cash', 'vch_type' => 'receipt', 'vch_no' => 59, 'from' => 6, 'details' => 'TRAIN TICKET', 'created_by' => 1, 'updated_by' => 1],
            ['ledger_id' => 625, 'amount' => 5500, 'date' => '2024-04-04', 'mode' => 'Cash', 'vch_type' => 'receipt', 'vch_no' => 60, 'from' => 6, 'details' => 'JAMA', 'created_by' => 1, 'updated_by' => 1],
            ['ledger_id' => 595, 'amount' => 74315, 'date' => '2024-05-21', 'mode' => 'Cash', 'vch_type' => 'receipt', 'vch_no' => 61, 'from' => 6, 'details' => 0, 'created_by' => 1, 'updated_by' => 1],
            ['ledger_id' => 142, 'amount' => 20000, 'date' => '2024-05-21', 'mode' => 'Cash', 'vch_type' => 'receipt', 'vch_no' => 62, 'from' => 6, 'details' => 'C TO SANJU', 'created_by' => 1, 'updated_by' => 1],
            ['ledger_id' => 135, 'amount' => 15000, 'date' => '2024-05-21', 'mode' => 'Cash', 'vch_type' => 'receipt', 'vch_no' => 63, 'from' => 6, 'details' => '', 'created_by' => 1, 'updated_by' => 1],
            ['ledger_id' => 143, 'amount' => 22000, 'date' => '2024-05-21', 'mode' => 'Cash', 'vch_type' => 'receipt', 'vch_no' => 64, 'from' => 6, 'details' => 'C TO SANJU', 'created_by' => 1, 'updated_by' => 1],
            ['ledger_id' => 144, 'amount' => 20000, 'date' => '2024-05-21', 'mode' => 'Cash', 'vch_type' => 'receipt', 'vch_no' => 65, 'from' => 6, 'details' => 'C TO SANJU', 'created_by' => 1, 'updated_by' => 1],
            ['ledger_id' => 124, 'amount' => 25000, 'date' => '2024-05-21', 'mode' => 'Cash', 'vch_type' => 'receipt', 'vch_no' => 66, 'from' => 6, 'details' => 'C TO SANJU', 'created_by' => 1, 'updated_by' => 1],
            ['ledger_id' => 127, 'amount' => 10000, 'date' => '2024-05-21', 'mode' => 'Cash', 'vch_type' => 'receipt', 'vch_no' => 67, 'from' => 6, 'details' => 'C TO SANJU', 'created_by' => 1, 'updated_by' => 1],
            ['ledger_id' => 591, 'amount' => 6700, 'date' => '2024-05-21', 'mode' => 'Cash', 'vch_type' => 'receipt', 'vch_no' => 68, 'from' => 6, 'details' => 'C TO SANJU', 'created_by' => 1, 'updated_by' => 1],
            ['ledger_id' => 299, 'amount' => 175300, 'date' => '2024-05-21', 'mode' => 'Cash', 'vch_type' => 'receipt', 'vch_no' => 69, 'from' => 6, 'details' => 'ATAC', 'created_by' => 1, 'updated_by' => 1],
            ['ledger_id' => 287, 'amount' => 50000, 'date' => '2024-05-21', 'mode' => 'Cash', 'vch_type' => 'receipt', 'vch_no' => 70, 'from' => 6, 'details' => 'TO ATRE BSL', 'created_by' => 1, 'updated_by' => 1],
            ['ledger_id' => 629, 'amount' => 24700, 'date' => '2024-04-05', 'mode' => 'Cash', 'vch_type' => 'receipt', 'vch_no' => 71, 'from' => 6, 'details' => 'DV', 'created_by' => 1, 'updated_by' => 1],
            ['ledger_id' => 630, 'amount' => 104450, 'date' => '2024-04-05', 'mode' => 'Cash', 'vch_type' => 'receipt', 'vch_no' => 72, 'from' => 6, 'details' => '', 'created_by' => 1, 'updated_by' => 1],
            ['ledger_id' => 310, 'amount' => 30000, 'date' => '2024-04-05', 'mode' => 'Cash', 'vch_type' => 'receipt', 'vch_no' => 73, 'from' => 6, 'details' => 'ALL CLEAR DUKAN ACCOUNT', 'created_by' => 1, 'updated_by' => 1],
            ['ledger_id' => 137, 'amount' => 20000, 'date' => '2024-04-05', 'mode' => 'Cash', 'vch_type' => 'receipt', 'vch_no' => 74, 'from' => 6, 'details' => '', 'created_by' => 1, 'updated_by' => 1],
            ['ledger_id' => 140, 'amount' => 14200, 'date' => '2024-04-05', 'mode' => 'Cash', 'vch_type' => 'receipt', 'vch_no' => 75, 'from' => 6, 'details' => '', 'created_by' => 1, 'updated_by' => 1],
            ['ledger_id' => 145, 'amount' => 15440, 'date' => '2024-04-05', 'mode' => 'Cash', 'vch_type' => 'receipt', 'vch_no' => 76, 'from' => 6, 'details' => '', 'created_by' => 1, 'updated_by' => 1],
            ['ledger_id' => 615, 'amount' => 123850, 'date' => '2024-04-06', 'mode' => 'Cash', 'vch_type' => 'receipt', 'vch_no' => 77, 'from' => 6, 'details' => '', 'created_by' => 1, 'updated_by' => 1],
            ['ledger_id' => 218, 'amount' => 5000, 'date' => '2024-04-06', 'mode' => 'Cash', 'vch_type' => 'receipt', 'vch_no' => 78, 'from' => 6, 'details' => '', 'created_by' => 1, 'updated_by' => 1],
            ['ledger_id' => 219, 'amount' => 3000, 'date' => '2024-04-06', 'mode' => 'Cash', 'vch_type' => 'receipt', 'vch_no' => 79, 'from' => 6, 'details' => '', 'created_by' => 1, 'updated_by' => 1],
            ['ledger_id' => 260, 'amount' => 2200, 'date' => '2024-04-06', 'mode' => 'Cash', 'vch_type' => 'receipt', 'vch_no' => 80, 'from' => 6, 'details' => '', 'created_by' => 1, 'updated_by' => 1],
            ['ledger_id' => 258, 'amount' => 4200, 'date' => '2024-04-06', 'mode' => 'Cash', 'vch_type' => 'receipt', 'vch_no' => 81, 'from' => 6, 'details' => '', 'created_by' => 1, 'updated_by' => 1],
            ['ledger_id' => 274, 'amount' => 5660, 'date' => '2024-04-06', 'mode' => 'Cash', 'vch_type' => 'receipt', 'vch_no' => 82, 'from' => 6, 'details' => '', 'created_by' => 1, 'updated_by' => 1],
            ['ledger_id' => 273, 'amount' => 2000, 'date' => '2024-04-06', 'mode' => 'Cash', 'vch_type' => 'receipt', 'vch_no' => 83, 'from' => 6, 'details' => '', 'created_by' => 1, 'updated_by' => 1],
            ['ledger_id' => 208, 'amount' => 1500, 'date' => '2024-04-06', 'mode' => 'Cash', 'vch_type' => 'receipt', 'vch_no' => 84, 'from' => 6, 'details' => '', 'created_by' => 1, 'updated_by' => 1],
            ['ledger_id' => 277, 'amount' => 12200, 'date' => '2024-04-06', 'mode' => 'Cash', 'vch_type' => 'receipt', 'vch_no' => 85, 'from' => 6, 'details' => '', 'created_by' => 1, 'updated_by' => 1],
            ['ledger_id' => 593, 'amount' => 400000, 'date' => '2024-04-06', 'mode' => 'Cash', 'vch_type' => 'receipt', 'vch_no' => 86, 'from' => 6, 'details' => 'RAJESH VARYANI ENTRY', 'created_by' => 1, 'updated_by' => 1],
            ['ledger_id' => 270, 'amount' => 15000, 'date' => '2024-04-06', 'mode' => 'Cash', 'vch_type' => 'receipt', 'vch_no' => 87, 'from' => 6, 'details' => '', 'created_by' => 1, 'updated_by' => 1],
            ['ledger_id' => 648, 'amount' => 1000, 'date' => '2024-04-06', 'mode' => 'Cash', 'vch_type' => 'receipt', 'vch_no' => 88, 'from' => 6, 'details' => '', 'created_by' => 1, 'updated_by' => 1],
            ['ledger_id' => 649, 'amount' => 1800, 'date' => '2024-04-06', 'mode' => 'Cash', 'vch_type' => 'receipt', 'vch_no' => 89, 'from' => 6, 'details' => '', 'created_by' => 1, 'updated_by' => 1],
            ['ledger_id' => 592, 'amount' => 9500, 'date' => '2024-04-07', 'mode' => 'Cash', 'vch_type' => 'receipt', 'vch_no' => 90, 'from' => 6, 'details' => 'S-3310', 'created_by' => 1, 'updated_by' => 1],
            ['ledger_id' => 596, 'amount' => 2480, 'date' => '2024-04-07', 'mode' => 'Cash', 'vch_type' => 'receipt', 'vch_no' => 91, 'from' => 6, 'details' => '', 'created_by' => 1, 'updated_by' => 1],
            ['ledger_id' => 125, 'amount' => 6000, 'date' => '2024-04-07', 'mode' => 'Cash', 'vch_type' => 'receipt', 'vch_no' => 92, 'from' => 6, 'details' => '', 'created_by' => 1, 'updated_by' => 1],
            ['ledger_id' => 146, 'amount' => 10000, 'date' => '2024-04-07', 'mode' => '', 'vch_type' => 'receipt', 'vch_no' => 93, 'from' => 6, 'details' => '', 'created_by' => 1, 'updated_by' => 1],
            ['ledger_id' => 121, 'amount' => 24035, 'date' => '2024-04-07', 'mode' => 'Cash', 'vch_type' => 'receipt', 'vch_no' => 94, 'from' => 6, 'details' => '', 'created_by' => 1, 'updated_by' => 1],
            ['ledger_id' => 138, 'amount' => 15400, 'date' => '2024-04-07', 'mode' => 'Cash', 'vch_type' => 'receipt', 'vch_no' => 95, 'from' => 6, 'details' => '', 'created_by' => 1, 'updated_by' => 1],
            ['ledger_id' => 132, 'amount' => 5970, 'date' => '2024-04-07', 'mode' => 'Cash', 'vch_type' => 'receipt', 'vch_no' => 96, 'from' => 6, 'details' => '', 'created_by' => 1, 'updated_by' => 1],
            ['ledger_id' => 652, 'amount' => 2000, 'date' => '2024-04-07', 'mode' => 'Cash', 'vch_type' => 'receipt', 'vch_no' => 97, 'from' => 6, 'details' => '', 'created_by' => 1, 'updated_by' => 1],
            ['ledger_id' => 653, 'amount' => 51400, 'date' => '2024-04-07', 'mode' => 'Cash', 'vch_type' => 'receipt', 'vch_no' => 98, 'from' => 6, 'details' => '', 'created_by' => 1, 'updated_by' => 1],
            ['ledger_id' => 605, 'amount' => 2400, 'date' => '2024-04-08', 'mode' => 'Cash', 'vch_type' => 'receipt', 'vch_no' => 99, 'from' => 6, 'details' => '', 'created_by' => 1, 'updated_by' => 1],
            ['ledger_id' => 659, 'amount' => 120050, 'date' => '2024-04-08', 'mode' => 'Cash', 'vch_type' => 'receipt', 'vch_no' => 100, 'from' => 6, 'details' => '', 'created_by' => 1, 'updated_by' => 1],
            ['ledger_id' => 592, 'amount' => 5700, 'date' => '2024-04-08', 'mode' => 'Cash', 'vch_type' => 'receipt', 'vch_no' => 101, 'from' => 6, 'details' => 'S-59', 'created_by' => 1, 'updated_by' => 1],
            ['ledger_id' => 327, 'amount' => 39750, 'date' => '2024-04-08', 'mode' => 'Cash', 'vch_type' => 'receipt', 'vch_no' => 102, 'from' => 6, 'details' => '', 'created_by' => 1, 'updated_by' => 1],
            ['ledger_id' => 604, 'amount' => 86500, 'date' => '2024-04-08', 'mode' => 'Cash', 'vch_type' => 'receipt', 'vch_no' => 103, 'from' => 6, 'details' => '', 'created_by' => 1, 'updated_by' => 1],
            ['ledger_id' => 660, 'amount' => 1000, 'date' => '2024-04-08', 'mode' => 'Cash', 'vch_type' => 'receipt', 'vch_no' => 104, 'from' => 6, 'details' => 'RETURN', 'created_by' => 1, 'updated_by' => 1],
            ['ledger_id' => 593, 'amount' => 15000, 'date' => '2024-04-08', 'mode' => 'Cash', 'vch_type' => 'receipt', 'vch_no' => 105, 'from' => 6, 'details' => 'MANISH MARKET RENT GYAN BRO', 'created_by' => 1, 'updated_by' => 1],
            ['ledger_id' => 114, 'amount' => 10000, 'date' => '2024-04-08', 'mode' => 'Cash', 'vch_type' => 'receipt', 'vch_no' => 106, 'from' => 6, 'details' => '', 'created_by' => 1, 'updated_by' => 1],
            ['ledger_id' => 110, 'amount' => 8000, 'date' => '2024-04-08', 'mode' => 'Cash', 'vch_type' => 'receipt', 'vch_no' => 107, 'from' => 6, 'details' => '', 'created_by' => 1, 'updated_by' => 1],
            ['ledger_id' => 661, 'amount' => 20000, 'date' => '2024-04-08', 'mode' => 'Cash', 'vch_type' => 'receipt', 'vch_no' => 108, 'from' => 6, 'details' => '', 'created_by' => 1, 'updated_by' => 1],
            ['ledger_id' => 106, 'amount' => 4800, 'date' => '2024-04-08', 'mode' => 'Cash', 'vch_type' => 'receipt', 'vch_no' => 109, 'from' => 6, 'details' => '', 'created_by' => 1, 'updated_by' => 1],
            ['ledger_id' => 103, 'amount' => 10200, 'date' => '2024-04-08', 'mode' => 'Cash', 'vch_type' => 'receipt', 'vch_no' => 110, 'from' => 6, 'details' => '', 'created_by' => 1, 'updated_by' => 1],
            ['ledger_id' => 104, 'amount' => 20000, 'date' => '2024-04-08', 'mode' => 'Cash', 'vch_type' => 'receipt', 'vch_no' => 111, 'from' => 6, 'details' => '', 'created_by' => 1, 'updated_by' => 1],
            ['ledger_id' => 105, 'amount' => 21400, 'date' => '2024-04-08', 'mode' => 'Cash', 'vch_type' => 'receipt', 'vch_no' => 112, 'from' => 6, 'details' => '', 'created_by' => 1, 'updated_by' => 1],
            ['ledger_id' => 108, 'amount' => 20000, 'date' => '2024-04-08', 'mode' => 'Cash', 'vch_type' => 'receipt', 'vch_no' => 113, 'from' => 6, 'details' => '', 'created_by' => 1, 'updated_by' => 1],
            ['ledger_id' => 109, 'amount' => 35000, 'date' => '2024-04-08', 'mode' => 'Cash', 'vch_type' => 'receipt', 'vch_no' => 114, 'from' => 6, 'details' => '', 'created_by' => 1, 'updated_by' => 1],
            ['ledger_id' => 118, 'amount' => 20700, 'date' => '2024-04-08', 'mode' => 'Cash', 'vch_type' => 'receipt', 'vch_no' => 115, 'from' => 6, 'details' => '', 'created_by' => 1, 'updated_by' => 1],
            ['ledger_id' => 591, 'amount' => 6000, 'date' => '2024-04-08', 'mode' => 'Cash', 'vch_type' => 'receipt', 'vch_no' => 116, 'from' => 6, 'details' => '', 'created_by' => 1, 'updated_by' => 1],
            ['ledger_id' => 621, 'amount' => 64720, 'date' => '2024-04-08', 'mode' => 'Cash', 'vch_type' => 'receipt', 'vch_no' => 117, 'from' => 6, 'details' => '', 'created_by' => 1, 'updated_by' => 1],
            ['ledger_id' => 595, 'amount' => 5000, 'date' => '2024-04-08', 'mode' => 'Cash', 'vch_type' => 'receipt', 'vch_no' => 118, 'from' => 6, 'details' => '', 'created_by' => 1, 'updated_by' => 1],
            ['ledger_id' => 596, 'amount' => 470, 'date' => '2024-04-08', 'mode' => 'Cash', 'vch_type' => 'receipt', 'vch_no' => 119, 'from' => 6, 'details' => '', 'created_by' => 1, 'updated_by' => 1],
            ['ledger_id' => 662, 'amount' => 27800, 'date' => '2024-04-08', 'mode' => 'Cash', 'vch_type' => 'receipt', 'vch_no' => 120, 'from' => 6, 'details' => '', 'created_by' => 1, 'updated_by' => 1],
            ['ledger_id' => 621, 'amount' => 21750, 'date' => '2024-04-08', 'mode' => 'Cash', 'vch_type' => 'receipt', 'vch_no' => 121, 'from' => 6, 'details' => '', 'created_by' => 1, 'updated_by' => 1],
        ['ledger_id' => 593, 'amount' => 30000, 'date' => '2024-05-13', 'mode' => 'Cash', 'vch_type' => 'payment', 'vch_no' => 1, 'from' => 6, 'details' => 'NPM HDFC ACCOUNT FROM SANJU COLLECTION', 'created_by' => 1, 'updated_by' => 1],
['ledger_id' => 594, 'amount' => 5150, 'date' => '2024-05-13', 'mode' => 'Cash', 'vch_type' => 'payment', 'vch_no' => 2, 'from' => 6, 'details' => 'SANJAY MARKETING EXP NANDURBAR AND SONGAD ', 'created_by' => 1, 'updated_by' => 1],
['ledger_id' => 591, 'amount' => 6700, 'date' => '2024-05-13', 'mode' => 'Cash', 'vch_type' => 'payment', 'vch_no' => 3, 'from' => 6, 'details' => 'TEMP FOR KHANDWA LINE', 'created_by' => 1, 'updated_by' => 1],
['ledger_id' => 595, 'amount' => 2000, 'date' => '2024-05-13', 'mode' => 'Cash', 'vch_type' => 'payment', 'vch_no' => 4, 'from' => 6, 'details' => 'TEMP FOR NANDURBAR SONGAD MARKETING', 'created_by' => 1, 'updated_by' => 1],
['ledger_id' => 600, 'amount' => 1000, 'date' => '2024-05-12', 'mode' => 'Cash', 'vch_type' => 'payment', 'vch_no' => 5, 'from' => 6, 'details' => 'DILIP SINGH ON ACCOUNT', 'created_by' => 1, 'updated_by' => 1],
['ledger_id' => 593, 'amount' => 14350, 'date' => '2024-05-12', 'mode' => 'Cash', 'vch_type' => 'payment', 'vch_no' => 6, 'from' => 6, 'details' => 'MENRUN SITE MANOJ SAINI TO DEVA', 'created_by' => 1, 'updated_by' => 1],
['ledger_id' => 593, 'amount' => 1400, 'date' => '2024-05-12', 'mode' => 'Cash', 'vch_type' => 'payment', 'vch_no' => 7, 'from' => 6, 'details' => 'MEHRUN SITE TO DEVA WEAKLY', 'created_by' => 1, 'updated_by' => 1],
['ledger_id' => 601, 'amount' => 100, 'date' => '2024-05-12', 'mode' => 'Cash', 'vch_type' => 'payment', 'vch_no' => 8, 'from' => 6, 'details' => 'NXG', 'created_by' => 1, 'updated_by' => 1],
['ledger_id' => 602, 'amount' => 13800, 'date' => '2024-05-12', 'mode' => 'Cash', 'vch_type' => 'payment', 'vch_no' => 9, 'from' => 6, 'details' => 'DANA MAJURI WEAKLY', 'created_by' => 1, 'updated_by' => 1],
['ledger_id' => 603, 'amount' => 408000, 'date' => '2024-05-14', 'mode' => 'Cash', 'vch_type' => 'payment', 'vch_no' => 10, 'from' => 6, 'details' => 'BY RITESH', 'created_by' => 1, 'updated_by' => 1],
['ledger_id' => 593, 'amount' => 50000, 'date' => '2024-04-01', 'mode' => 'Cash', 'vch_type' => 'payment', 'vch_no' => 11, 'from' => 6, 'details' => 'KPM 1 WARA ARIL ADVANCE', 'created_by' => 1, 'updated_by' => 1],
['ledger_id' => 600, 'amount' => 220, 'date' => '2024-04-01', 'mode' => 'Cash', 'vch_type' => 'payment', 'vch_no' => 12, 'from' => 6, 'details' => 'MAHARASHTA MAP', 'created_by' => 1, 'updated_by' => 1],
['ledger_id' => 609, 'amount' => 3000, 'date' => '2024-04-01', 'mode' => 'Cash', 'vch_type' => 'payment', 'vch_no' => 13, 'from' => 6, 'details' => 'MEHKAR ADV FRIEGHT', 'created_by' => 1, 'updated_by' => 1],
['ledger_id' => 610, 'amount' => 1288, 'date' => '2024-04-01', 'mode' => 'Cash', 'vch_type' => 'payment', 'vch_no' => 14, 'from' => 6, 'details' => 'ALL CLEAR', 'created_by' => 1, 'updated_by' => 1],
['ledger_id' => 601, 'amount' => 200, 'date' => '2024-04-01', 'mode' => 'Cash', 'vch_type' => 'payment', 'vch_no' => 15, 'from' => 6, 'details' => 'SAGAR PETROL', 'created_by' => 1, 'updated_by' => 1],
['ledger_id' => 593, 'amount' => 11000, 'date' => '2024-04-01', 'mode' => 'Cash', 'vch_type' => 'payment', 'vch_no' => 16, 'from' => 6, 'details' => 'MEHRUN SITE SANTOSH KUMBHAR BRICK 2000*5.50', 'created_by' => 1, 'updated_by' => 1],
['ledger_id' => 594, 'amount' => 10650, 'date' => '2024-04-01', 'mode' => 'Cash', 'vch_type' => 'payment', 'vch_no' => 17, 'from' => 6, 'details' => '', 'created_by' => 1, 'updated_by' => 1],
['ledger_id' => 611, 'amount' => 25000, 'date' => '2024-04-01', 'mode' => 'Cash', 'vch_type' => 'payment', 'vch_no' => 18, 'from' => 6, 'details' => '', 'created_by' => 1, 'updated_by' => 1],
['ledger_id' => 612, 'amount' => 8220, 'date' => '2024-04-01', 'mode' => 'Cash', 'vch_type' => 'payment', 'vch_no' => 19, 'from' => 6, 'details' => 'SALARY ALL CLEAR', 'created_by' => 1, 'updated_by' => 1],
['ledger_id' => 589, 'amount' => 50, 'date' => '2024-04-01', 'mode' => 'Cash', 'vch_type' => 'payment', 'vch_no' => 20, 'from' => 6, 'details' => 'KATA EXP', 'created_by' => 1, 'updated_by' => 1],
['ledger_id' => 600, 'amount' => 180, 'date' => '2024-04-01', 'mode' => 'Cash', 'vch_type' => 'payment', 'vch_no' => 21, 'from' => 6, 'details' => 'HAND GLOVES', 'created_by' => 1, 'updated_by' => 1],
['ledger_id' => 530, 'amount' => 50, 'date' => '2024-04-01', 'mode' => 'Cash', 'vch_type' => 'payment', 'vch_no' => 22, 'from' => 6, 'details' => 'ADVANCE', 'created_by' => 1, 'updated_by' => 1],
['ledger_id' => 409, 'amount' => 7000, 'date' => '2024-04-01', 'mode' => 'Cash', 'vch_type' => 'payment', 'vch_no' => 23, 'from' => 6, 'details' => 'ON SALARY', 'created_by' => 1, 'updated_by' => 1],
['ledger_id' => 613, 'amount' => 2500, 'date' => '2024-04-01', 'mode' => 'Cash', 'vch_type' => 'payment', 'vch_no' => 24, 'from' => 6, 'details' => 'ADVANCE', 'created_by' => 1, 'updated_by' => 1],
['ledger_id' => 531, 'amount' => 10000, 'date' => '2024-04-01', 'mode' => 'Cash', 'vch_type' => 'payment', 'vch_no' => 25, 'from' => 6, 'details' => 'MARCH SALARY', 'created_by' => 1, 'updated_by' => 1],
['ledger_id' => 593, 'amount' => 890, 'date' => '2024-04-01', 'mode' => 'Cash', 'vch_type' => 'payment', 'vch_no' => 26, 'from' => 6, 'details' => 'HOME MEDICINE', 'created_by' => 1, 'updated_by' => 1],
['ledger_id' => 614, 'amount' => 4000, 'date' => '2024-04-01', 'mode' => 'Cash', 'vch_type' => 'payment', 'vch_no' => 27, 'from' => 6, 'details' => 'WEAKLY', 'created_by' => 1, 'updated_by' => 1],
['ledger_id' => 533, 'amount' => 14500, 'date' => '2024-04-01', 'mode' => 'Cash', 'vch_type' => 'payment', 'vch_no' => 28, 'from' => 6, 'details' => 'MARCH SALARY', 'created_by' => 1, 'updated_by' => 1],
['ledger_id' => 593, 'amount' => 100, 'date' => '2024-04-01', 'mode' => 'Cash', 'vch_type' => 'payment', 'vch_no' => 29, 'from' => 6, 'details' => 'CHINCHOLII BHADA TO GAURAKH RATHOD', 'created_by' => 1, 'updated_by' => 1],
['ledger_id' => 597, 'amount' => 150, 'date' => '2024-04-01', 'mode' => 'Cash', 'vch_type' => 'payment', 'vch_no' => 30, 'from' => 6, 'details' => 'PATTI UNLOADED AT CHINCHOLI', 'created_by' => 1, 'updated_by' => 1],
['ledger_id' => 601, 'amount' => 1400, 'date' => '2024-04-01', 'mode' => 'Cash', 'vch_type' => 'payment', 'vch_no' => 31, 'from' => 6, 'details' => 'PARVEJ ADV FOR APRIL', 'created_by' => 1, 'updated_by' => 1],
['ledger_id' => 595, 'amount' => 2000, 'date' => '2024-04-01', 'mode' => 'Cash', 'vch_type' => 'payment', 'vch_no' => 32, 'from' => 6, 'details' => 'LINE', 'created_by' => 1, 'updated_by' => 1],
['ledger_id' => 532, 'amount' => 5000, 'date' => '2024-04-01', 'mode' => 'Cash', 'vch_type' => 'payment', 'vch_no' => 33, 'from' => 6, 'details' => 'ON ACCOUNT SALARY', 'created_by' => 1, 'updated_by' => 1],
['ledger_id' => 594, 'amount' => 5000, 'date' => '2024-04-02', 'mode' => 'Cash', 'vch_type' => 'payment', 'vch_no' => 34, 'from' => 6, 'details' => 'SWIFT MAINTANANCE', 'created_by' => 1, 'updated_by' => 1],
['ledger_id' => 601, 'amount' => 100, 'date' => '2024-04-02', 'mode' => 'Cash', 'vch_type' => 'payment', 'vch_no' => 35, 'from' => 6, 'details' => 'ACSES', 'created_by' => 1, 'updated_by' => 1],
['ledger_id' => 589, 'amount' => 200, 'date' => '2024-04-02', 'mode' => 'Cash', 'vch_type' => 'payment', 'vch_no' => 36, 'from' => 6, 'details' => 'KATA EXP P-758', 'created_by' => 1, 'updated_by' => 1],
['ledger_id' => 331, 'amount' => 500, 'date' => '2024-04-02', 'mode' => 'Cash', 'vch_type' => 'payment', 'vch_no' => 37, 'from' => 6, 'details' => 'BAL FRIEGHT ', 'created_by' => 1, 'updated_by' => 1],
['ledger_id' => 609, 'amount' => 500, 'date' => '2024-04-02', 'mode' => 'Cash', 'vch_type' => 'payment', 'vch_no' => 38, 'from' => 6, 'details' => 'AMBICA TENT NASIK BAL FR', 'created_by' => 1, 'updated_by' => 1],
['ledger_id' => 607, 'amount' => 5000, 'date' => '2024-04-02', 'mode' => 'Cash', 'vch_type' => 'payment', 'vch_no' => 39, 'from' => 6, 'details' => 'TEMP', 'created_by' => 1, 'updated_by' => 1],
['ledger_id' => 597, 'amount' => 2240, 'date' => '2024-04-02', 'mode' => 'Cash', 'vch_type' => 'payment', 'vch_no' => 40, 'from' => 6, 'details' => '', 'created_by' => 1, 'updated_by' => 1],
['ledger_id' => 619, 'amount' => 150, 'date' => '2024-02-04', 'mode' => 'Cash', 'vch_type' => 'payment', 'vch_no' => 41, 'from' => 6, 'details' => 'LOCALAUTO FARE', 'created_by' => 1, 'updated_by' => 1],
['ledger_id' => 609, 'amount' => 3500, 'date' => '2024-04-03', 'mode' => 'Cash', 'vch_type' => 'payment', 'vch_no' => 42, 'from' => 6, 'details' => 'ANUKUSH TENT', 'created_by' => 1, 'updated_by' => 1],
['ledger_id' => 425, 'amount' => 200, 'date' => '2024-04-03', 'mode' => 'Cash', 'vch_type' => 'payment', 'vch_no' => 43, 'from' => 6, 'details' => 'ADVANCE', 'created_by' => 1, 'updated_by' => 1],
['ledger_id' => 622, 'amount' => 50, 'date' => '2024-04-03', 'mode' => 'Cash', 'vch_type' => 'payment', 'vch_no' => 44, 'from' => 6, 'details' => 'ADVANCE', 'created_by' => 1, 'updated_by' => 1],
['ledger_id' => 426, 'amount' => 9000, 'date' => '2024-04-03', 'mode' => 'Cash', 'vch_type' => 'payment', 'vch_no' => 45, 'from' => 6, 'details' => 'MARCH SALARY', 'created_by' => 1, 'updated_by' => 1],
['ledger_id' => 428, 'amount' => 1000, 'date' => '2024-04-03', 'mode' => 'Cash', 'vch_type' => 'payment', 'vch_no' => 46, 'from' => 6, 'details' => 'ADVANCE', 'created_by' => 1, 'updated_by' => 1],
['ledger_id' => 628, 'amount' => 200000, 'date' => '2024-05-21', 'mode' => 'Cash', 'vch_type' => 'payment', 'vch_no' => 47, 'from' => 6, 'details' => 'TO NADIM', 'created_by' => 1, 'updated_by' => 1],
['ledger_id' => 600, 'amount' => 1750, 'date' => '2024-05-21', 'mode' => 'Cash', 'vch_type' => 'payment', 'vch_no' => 48, 'from' => 6, 'details' => 'TO JOGESHWARI BLADE', 'created_by' => 1, 'updated_by' => 1],
['ledger_id' => 589, 'amount' => 560, 'date' => '2024-05-21', 'mode' => 'Cash', 'vch_type' => 'payment', 'vch_no' => 49, 'from' => 6, 'details' => 'KATA P 124', 'created_by' => 1, 'updated_by' => 1],
['ledger_id' => 601, 'amount' => 100, 'date' => '2024-05-21', 'mode' => 'Cash', 'vch_type' => 'payment', 'vch_no' => 50, 'from' => 6, 'details' => 'ACESS', 'created_by' => 1, 'updated_by' => 1],
['ledger_id' => 593, 'amount' => 700, 'date' => '2024-05-21', 'mode' => 'Cash', 'vch_type' => 'payment', 'vch_no' => 51, 'from' => 6, 'details' => 'VERNA KEY REPAIR ', 'created_by' => 1, 'updated_by' => 1],
['ledger_id' => 597, 'amount' => 2030, 'date' => '2024-05-21', 'mode' => 'Cash', 'vch_type' => 'payment', 'vch_no' => 52, 'from' => 6, 'details' => 'P124 AND CP 224', 'created_by' => 1, 'updated_by' => 1],
['ledger_id' => 594, 'amount' => 3400, 'date' => '2024-05-21', 'mode' => 'Cash', 'vch_type' => 'payment', 'vch_no' => 53, 'from' => 6, 'details' => 'SWIFT DIESEL BOKARDAN', 'created_by' => 1, 'updated_by' => 1],
['ledger_id' => 609, 'amount' => 3000, 'date' => '2024-04-05', 'mode' => 'Cash', 'vch_type' => 'payment', 'vch_no' => 54, 'from' => 6, 'details' => 'ANKUSH TENT', 'created_by' => 1, 'updated_by' => 1],
['ledger_id' => 631, 'amount' => 10800, 'date' => '2024-04-05', 'mode' => 'Cash', 'vch_type' => 'payment', 'vch_no' => 55, 'from' => 6, 'details' => 'EBRO TRADING', 'created_by' => 1, 'updated_by' => 1],
['ledger_id' => 589, 'amount' => 510, 'date' => '2024-04-05', 'mode' => 'Cash', 'vch_type' => 'payment', 'vch_no' => 56, 'from' => 6, 'details' => 'KATA', 'created_by' => 1, 'updated_by' => 1],
['ledger_id' => 601, 'amount' => 130, 'date' => '2024-04-05', 'mode' => 'Cash', 'vch_type' => 'payment', 'vch_no' => 57, 'from' => 6, 'details' => 'PLEASURE', 'created_by' => 1, 'updated_by' => 1],
['ledger_id' => 600, 'amount' => 50, 'date' => '2024-04-05', 'mode' => 'Cash', 'vch_type' => 'payment', 'vch_no' => 58, 'from' => 6, 'details' => 'COTTON TAPE', 'created_by' => 1, 'updated_by' => 1],
['ledger_id' => 597, 'amount' => 1200, 'date' => '2024-04-05', 'mode' => 'Cash', 'vch_type' => 'payment', 'vch_no' => 59, 'from' => 6, 'details' => 'P-772', 'created_by' => 1, 'updated_by' => 1],
['ledger_id' => 632, 'amount' => 5000, 'date' => '2024-04-05', 'mode' => 'Cash', 'vch_type' => 'payment', 'vch_no' => 60, 'from' => 6, 'details' => 'ON ACCOUNT SALARY', 'created_by' => 1, 'updated_by' => 1],
['ledger_id' => 603, 'amount' => 500000, 'date' => '2024-04-05', 'mode' => 'Cash', 'vch_type' => 'payment', 'vch_no' => 61, 'from' => 6, 'details' => '', 'created_by' => 1, 'updated_by' => 1],
['ledger_id' => 593, 'amount' => 236000, 'date' => '2024-04-05', 'mode' => 'Cash', 'vch_type' => 'payment', 'vch_no' => 62, 'from' => 6, 'details' => 'SR NO 78-1  PLOT NO ..... TO SHARAD CHANDWANI BSL', 'created_by' => 1, 'updated_by' => 1],
['ledger_id' => 633, 'amount' => 3500, 'date' => '2024-04-05', 'mode' => 'Cash', 'vch_type' => 'payment', 'vch_no' => 63, 'from' => 6, 'details' => 'WEAKLY', 'created_by' => 1, 'updated_by' => 1],
['ledger_id' => 634, 'amount' => 1250, 'date' => '2024-04-05', 'mode' => 'Cash', 'vch_type' => 'payment', 'vch_no' => 64, 'from' => 6, 'details' => 'WEAKLY', 'created_by' => 1, 'updated_by' => 1],
['ledger_id' => 635, 'amount' => 1500, 'date' => '2024-04-05', 'mode' => 'Cash', 'vch_type' => 'payment', 'vch_no' => 65, 'from' => 6, 'details' => 'WEAKLY', 'created_by' => 1, 'updated_by' => 1],
['ledger_id' => 636, 'amount' => 1500, 'date' => '2024-04-05', 'mode' => 'Cash', 'vch_type' => 'payment', 'vch_no' => 66, 'from' => 6, 'details' => 'WEAKLY', 'created_by' => 1, 'updated_by' => 1],
['ledger_id' => 637, 'amount' => 1500, 'date' => '2024-04-05', 'mode' => 'Cash', 'vch_type' => 'payment', 'vch_no' => 67, 'from' => 6, 'details' => 'WEAKLY', 'created_by' => 1, 'updated_by' => 1],
['ledger_id' => 638, 'amount' => 1500, 'date' => '2024-04-05', 'mode' => 'Cash', 'vch_type' => 'payment', 'vch_no' => 68, 'from' => 6, 'details' => 'WEAKLY', 'created_by' => 1, 'updated_by' => 1],
['ledger_id' => 593, 'amount' => 12000, 'date' => '2024-04-05', 'mode' => 'Cash', 'vch_type' => 'payment', 'vch_no' => 69, 'from' => 6, 'details' => 'RNM 1 WARA', 'created_by' => 1, 'updated_by' => 1],
['ledger_id' => 600, 'amount' => 1050, 'date' => '2024-04-05', 'mode' => 'Cash', 'vch_type' => 'payment', 'vch_no' => 70, 'from' => 6, 'details' => 'BLADE AND CHINDI', 'created_by' => 1, 'updated_by' => 1],
['ledger_id' => 602, 'amount' => 35700, 'date' => '2024-04-05', 'mode' => 'Cash', 'vch_type' => 'payment', 'vch_no' => 71, 'from' => 6, 'details' => 'WEAKLY', 'created_by' => 1, 'updated_by' => 1],
['ledger_id' => 639, 'amount' => 7400, 'date' => '2024-04-05', 'mode' => 'Cash', 'vch_type' => 'payment', 'vch_no' => 72, 'from' => 6, 'details' => 'GRINDING MAJURI', 'created_by' => 1, 'updated_by' => 1],
['ledger_id' => 641, 'amount' => 7400, 'date' => '2024-04-05', 'mode' => 'Cash', 'vch_type' => 'payment', 'vch_no' => 73, 'from' => 6, 'details' => 'MARCH SALARY', 'created_by' => 1, 'updated_by' => 1],
['ledger_id' => 640, 'amount' => 3100, 'date' => '2024-04-05', 'mode' => 'Cash', 'vch_type' => 'payment', 'vch_no' => 74, 'from' => 6, 'details' => 'MARCH SALARY', 'created_by' => 1, 'updated_by' => 1],
['ledger_id' => 642, 'amount' => 850, 'date' => '2024-04-05', 'mode' => 'Cash', 'vch_type' => 'payment', 'vch_no' => 75, 'from' => 6, 'details' => 'WEAKLY', 'created_by' => 1, 'updated_by' => 1],
['ledger_id' => 643, 'amount' => 4260, 'date' => '2024-04-05', 'mode' => 'Cash', 'vch_type' => 'payment', 'vch_no' => 76, 'from' => 6, 'details' => 'DISEAL', 'created_by' => 1, 'updated_by' => 1],
['ledger_id' => 528, 'amount' => 2700, 'date' => '2024-04-05', 'mode' => 'Cash', 'vch_type' => 'payment', 'vch_no' => 77, 'from' => 6, 'details' => 'WEAKLY', 'created_by' => 1, 'updated_by' => 1],
['ledger_id' => 424, 'amount' => 200, 'date' => '2024-04-05', 'mode' => 'Cash', 'vch_type' => 'payment', 'vch_no' => 78, 'from' => 6, 'details' => 'ADVANCE', 'created_by' => 1, 'updated_by' => 1],
['ledger_id' => 645, 'amount' => 2500, 'date' => '2024-04-05', 'mode' => 'Cash', 'vch_type' => 'payment', 'vch_no' => 79, 'from' => 6, 'details' => 'WEAKLY', 'created_by' => 1, 'updated_by' => 1],
['ledger_id' => 646, 'amount' => 1600, 'date' => '2024-04-05', 'mode' => 'Cash', 'vch_type' => 'payment', 'vch_no' => 80, 'from' => 6, 'details' => 'WEAKLY', 'created_by' => 1, 'updated_by' => 1],
['ledger_id' => 424, 'amount' => 1800, 'date' => '2024-04-05', 'mode' => 'Cash', 'vch_type' => 'payment', 'vch_no' => 81, 'from' => 6, 'details' => 'WEAKLY', 'created_by' => 1, 'updated_by' => 1],
['ledger_id' => 649, 'amount' => 2190, 'date' => '2024-04-06', 'mode' => 'Cash', 'vch_type' => 'payment', 'vch_no' => 82, 'from' => 6, 'details' => '', 'created_by' => 1, 'updated_by' => 1],
['ledger_id' => 593, 'amount' => 9000, 'date' => '2024-04-06', 'mode' => 'Cash', 'vch_type' => 'payment', 'vch_no' => 83, 'from' => 6, 'details' => 'MEHRUN SITE GAURAKH RATHOD', 'created_by' => 1, 'updated_by' => 1],
['ledger_id' => 323, 'amount' => 9000, 'date' => '2024-04-06', 'mode' => 'Cash', 'vch_type' => 'payment', 'vch_no' => 84, 'from' => 6, 'details' => 'FRIEGHT S-3303', 'created_by' => 1, 'updated_by' => 1],
['ledger_id' => 631, 'amount' => 500, 'date' => '2024-04-06', 'mode' => 'Cash', 'vch_type' => 'payment', 'vch_no' => 85, 'from' => 6, 'details' => 'TROLLY WHEEL', 'created_by' => 1, 'updated_by' => 1],
['ledger_id' => 597, 'amount' => 300, 'date' => '2024-04-06', 'mode' => 'Cash', 'vch_type' => 'payment', 'vch_no' => 86, 'from' => 6, 'details' => 'MEHTAB HAMALI', 'created_by' => 1, 'updated_by' => 1],
['ledger_id' => 651, 'amount' => 15000, 'date' => '2024-04-06', 'mode' => 'Cash', 'vch_type' => 'payment', 'vch_no' => 87, 'from' => 6, 'details' => 'ADVANCE', 'created_by' => 1, 'updated_by' => 1],
['ledger_id' => 589, 'amount' => 60, 'date' => '2024-04-06', 'mode' => 'Cash', 'vch_type' => 'payment', 'vch_no' => 88, 'from' => 6, 'details' => 'MILK EXP', 'created_by' => 1, 'updated_by' => 1],
['ledger_id' => 593, 'amount' => 35000, 'date' => '2024-04-06', 'mode' => 'Cash', 'vch_type' => 'payment', 'vch_no' => 89, 'from' => 6, 'details' => 'AREN SCHOON FEED', 'created_by' => 1, 'updated_by' => 1],
['ledger_id' => 628, 'amount' => 140000, 'date' => '2024-04-06', 'mode' => 'Cash', 'vch_type' => 'payment', 'vch_no' => 90, 'from' => 6, 'details' => '', 'created_by' => 1, 'updated_by' => 1],
['ledger_id' => 654, 'amount' => 10000, 'date' => '2024-04-07', 'mode' => 'Cash', 'vch_type' => 'payment', 'vch_no' => 91, 'from' => 6, 'details' => 'for marketing', 'created_by' => 1, 'updated_by' => 1],
['ledger_id' => 655, 'amount' => 10000, 'date' => '2024-04-07', 'mode' => 'Cash', 'vch_type' => 'payment', 'vch_no' => 92, 'from' => 6, 'details' => 'FOR MARKETIBG', 'created_by' => 1, 'updated_by' => 1],
['ledger_id' => 593, 'amount' => 12150, 'date' => '2024-04-07', 'mode' => 'Cash', 'vch_type' => 'payment', 'vch_no' => 93, 'from' => 6, 'details' => 'MEHRUN MANOJ SAINI TO DEVA', 'created_by' => 1, 'updated_by' => 1],
['ledger_id' => 601, 'amount' => 100, 'date' => '2024-04-07', 'mode' => 'Cash', 'vch_type' => 'payment', 'vch_no' => 94, 'from' => 6, 'details' => 'ACSES', 'created_by' => 1, 'updated_by' => 1],
['ledger_id' => 656, 'amount' => 2300, 'date' => '2024-04-07', 'mode' => 'Cash', 'vch_type' => 'payment', 'vch_no' => 95, 'from' => 6, 'details' => '', 'created_by' => 1, 'updated_by' => 1],
['ledger_id' => 589, 'amount' => 40, 'date' => '2024-04-07', 'mode' => '', 'vch_type' => 'payment', 'vch_no' => 96, 'from' => 6, 'details' => 'STATIONARY', 'created_by' => 1, 'updated_by' => 1],
['ledger_id' => 593, 'amount' => 21790, 'date' => '2024-04-07', 'mode' => 'Cash', 'vch_type' => 'payment', 'vch_no' => 97, 'from' => 6, 'details' => 'MEHRUN SANTOSH PAWAR', 'created_by' => 1, 'updated_by' => 1],
['ledger_id' => 619, 'amount' => 190, 'date' => '2024-04-07', 'mode' => 'Cash', 'vch_type' => 'payment', 'vch_no' => 98, 'from' => 6, 'details' => 'TRANSPORT', 'created_by' => 1, 'updated_by' => 1],
['ledger_id' => 644, 'amount' => 1150, 'date' => '2024-04-07', 'mode' => 'Cash', 'vch_type' => 'payment', 'vch_no' => 99, 'from' => 6, 'details' => 'MOHAMAD', 'created_by' => 1, 'updated_by' => 1],
['ledger_id' => 600, 'amount' => 7000, 'date' => '2024-04-07', 'mode' => 'Cash', 'vch_type' => 'payment', 'vch_no' => 100, 'from' => 6, 'details' => 'SAGAR INDUSTRIES ALL CLEAR', 'created_by' => 1, 'updated_by' => 1],
['ledger_id' => 593, 'amount' => 17300, 'date' => '2024-04-07', 'mode' => 'Cash', 'vch_type' => 'payment', 'vch_no' => 101, 'from' => 6, 'details' => 'KPM JAIPUR TICKET', 'created_by' => 1, 'updated_by' => 1],
['ledger_id' => 624, 'amount' => 1390, 'date' => '2024-04-07', 'mode' => 'Cash', 'vch_type' => 'payment', 'vch_no' => 102, 'from' => 6, 'details' => 'HALIM TICKET', 'created_by' => 1, 'updated_by' => 1],
['ledger_id' => 655, 'amount' => 810, 'date' => '2024-04-07', 'mode' => 'Cash', 'vch_type' => 'payment', 'vch_no' => 103, 'from' => 6, 'details' => 'MUMBAI TICKET', 'created_by' => 1, 'updated_by' => 1],
['ledger_id' => 657, 'amount' => 6000, 'date' => '2024-04-07', 'mode' => 'Cash', 'vch_type' => 'payment', 'vch_no' => 104, 'from' => 6, 'details' => 'ADVANCE', 'created_by' => 1, 'updated_by' => 1],
['ledger_id' => 600, 'amount' => 7500, 'date' => '2024-04-07', 'mode' => 'Cash', 'vch_type' => 'payment', 'vch_no' => 105, 'from' => 6, 'details' => '', 'created_by' => 1, 'updated_by' => 1],
['ledger_id' => 658, 'amount' => 500, 'date' => '2024-04-07', 'mode' => 'Cash', 'vch_type' => 'payment', 'vch_no' => 106, 'from' => 6, 'details' => 'ADV', 'created_by' => 1, 'updated_by' => 1],
['ledger_id' => 593, 'amount' => 75058, 'date' => '2024-04-08', 'mode' => 'Cash', 'vch_type' => 'payment', 'vch_no' => 107, 'from' => 6, 'details' => 'SHORT BY NPM', 'created_by' => 1, 'updated_by' => 1],
['ledger_id' => 660, 'amount' => 1000, 'date' => '2024-04-08', 'mode' => '', 'vch_type' => 'payment', 'vch_no' => 108, 'from' => 6, 'details' => '', 'created_by' => 1, 'updated_by' => 1],
['ledger_id' => 589, 'amount' => 1351, 'date' => '2024-04-08', 'mode' => 'Cash', 'vch_type' => 'payment', 'vch_no' => 109, 'from' => 6, 'details' => 'CHILLAR EXP', 'created_by' => 1, 'updated_by' => 1],
        ];
        DB::table('vch_payment_receipts')->insert($paymentReceipt);
    }
}
