<?php



define('GROUP_INCOME', 1);
define('GROUP_EXPENSES', 2);
define('GROUP_ASSETS', 3);
define('GROUP_LIABILITIES', 4);
define('GROUP_CURRENT_ASSETS', 5);
define('GROUP_FIXED_ASSETS', 6);
define('GROUP_INVESTMENTS', 7);
define('GROUP_MISC_EXPENSES_ASSET', 8);
define('GROUP_BANK_ACCOUNTS', 9);
define('GROUP_BRANCH_DIVISIONS', 10);
define('GROUP_CAPITAL_ACCOUNT', 11);
define('GROUP_CURRENT_LIABILITIES', 12);
define('GROUP_LOANS_LIABILITY', 13);
define('GROUP_SUSPENSE_ACCOUNT', 14);
define('GROUP_PROFIT_LOSS_ACCOUNT', 15);
define('GROUP_DIRECT_EXPENSES', 16);
define('GROUP_INDIRECT_EXPENSES', 17);
define('GROUP_PURCHASE_ACCOUNTS', 18);
define('GROUP_DIRECT_INCOMES', 19);
define('GROUP_INDIRECT_INCOMES', 20);
define('GROUP_SALES_ACCOUNTS', 21);
define('GROUP_CASH_IN_HAND', 22);
define('GROUP_LOANS_ADVANCES_ASSETS', 23);
define('GROUP_SUNDRY_DEBTORS_CUSTOMERS', 24);
define('GROUP_DUTIES_TAXES', 25);
define('GROUP_SUNDRY_CREDITORS_SUPPLIERS', 26);
define('GROUP_SECURED_LOANS', 27);
define('GROUP_UNSECURED_LOANS', 28);
define('GROUP_SALARY_PAYABLE', 29);
define('LEDGER_CGST',3);
define('LEDGER_SGST', 4);
define('LEDGER_IGST', 5);

?>